import { chordText, reorderChordTransform } from "./src/transformChords";
import {
  consolidateConsecutiveNotesTransform,
  duplicateLengthTransform,
  divideLengthTransform,
  sortedLengthsObj,
} from "./src/transformRests";
import {
  isLetter,
  isNoteToken,
  isOctaveToken,
  isAlterationToken,
  isPitchToken,
  isRhythmToken,
  NOTES_LOWERCASE,
  NOTES_UPPERCASE,
  dispatcherFunction,
  noteDispatcher,
} from "./src/dispatcher";
import {
  isNomenclatureTag,
  isNomenclatureLine,
  jumpToEndOfNomenclatureTag,
  jumpToEndOfNomenclatureLine,
  jumpToEndOfSymbol,
} from "./src/parseNomenclature";
import {
  findKeySignature,
  findUnalteredPitch,
  findNotesInKey,
} from "./src/parsekeySignature";
import {
  abcText,
  annotationCommandEnum,
  annotationStyle,
  instrumentFamilies,
  InstrumentCalls,
  findInstrumentCalls,
  createInstrumentationRoutine,
  parseUniqueTags,
} from "./src/annotationsActions";
import { parseAnnotation } from "./src/parseAnnotation";
import {
  isHeaderLine,
  separateHeaderAndBody,
  addNomenclatureToHeader,
  buildBodyFromInstruments,
} from "./src/fileStructureActions";
import {
  isLowerCase,
  octaviateDownTransform,
  octaviateUpTransform,
  convertToRestTransform,
  noteHeight,
  KeyIndicationType,
  convertToEnharmoniaTransform,
  transposeHalfStepDownTransform,
  transposeHalfStepUpTransform,
  transposeStepUpTransform,
  transposeStepDownTransform,
  contextObj,
  TransformFunction,
} from "./src/transformPitches";
import { parseRhythmToken, parseNote } from "./src/parseNotes";

export {
  abcText,
  addNomenclatureToHeader,
  annotationCommandEnum,
  annotationStyle,
  buildBodyFromInstruments,
  chordText,
  consolidateConsecutiveNotesTransform,
  contextObj,
  convertToEnharmoniaTransform,
  convertToRestTransform,
  createInstrumentationRoutine,
  noteDispatcher as dispatcher,
  dispatcherFunction,
  divideLengthTransform,
  duplicateLengthTransform,
  findInstrumentCalls,
  findKeySignature,
  findNotesInKey,
  findUnalteredPitch,
  InstrumentCalls,
  instrumentFamilies,
  isAlterationToken,
  isHeaderLine,
  isLetter,
  isLowerCase,
  isNomenclatureLine,
  isNomenclatureTag,
  isNoteToken,
  isOctaveToken,
  isPitchToken,
  isRhythmToken,
  jumpToEndOfNomenclatureLine,
  jumpToEndOfNomenclatureTag,
  jumpToEndOfSymbol,
  KeyIndicationType,
  noteHeight,
  NOTES_LOWERCASE,
  NOTES_UPPERCASE,
  octaviateDownTransform,
  octaviateUpTransform,
  parseAnnotation,
  parseNote,
  parseRhythmToken,
  parseUniqueTags,
  reorderChordTransform as reorderChord,
  separateHeaderAndBody,
  sortedLengthsObj,
  TransformFunction,
  transposeHalfStepDownTransform,
  transposeHalfStepUpTransform,
  transposeStepDownTransform,
  transposeStepUpTransform,
};
